-- Create table
CREATE TABLE products (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name varchar(40) NOT NULL,slug varchar(40) NOT NULL,image varchar(60),description varchar(500),need varchar(20),product_type varchar(20),price integer NOT NULL);

-- Query the information in the table
SELECT*FROM PRODUCTS;
-- Insert information into table
INSERT INTO products (name,slug,image,description,need,product_type,price) VALUES ('URIAGE THERMAL WATER','uriage-thermal-water','/images/eau-thermale.png','Uriage Thermal Water is a skincare water for daily use, a powerful treatment formulated with trace elements and mineral salts, a source of radiance for your skin.','Face Care','water',10),
('AGE PROTECT - MULTI-ACTION CREAM','age-protect-multi-action-cream','/images/age-protect.png','This smooth cream acts on both signs of aging and daily aggressions damaging the skin: blue light, UV rays, pollution, stress, fatigue... Enriched with moisturizing active ingredients, the skin is perfectly hydrated and supple.','Face Care','cream',25),
('BEBE - 1ST CLEANSING WATER','bebe-1st.cleansing water','/images/bebe.png','With soothing Uriage Thermal Water and enriched with moisturizing and softening active ingredients, 1st Cleansing Water leaves the skin clean, soft and delicately scented.','Baby Care','water',16);